version: "3.0"

services:
  gateway-service-app:
    image: gateway-service-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service-microservices_course
    environment:
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
    ports:
      - "9090:9090"
    networks:
      - service-registry_default
      - service-configuration_default

networks:
  service-registry_default:
    external: true
  service-configuration_default:
    external: true
